### ISSUE TITLE
Feature: User can customize a meal plan for each day of the week. 

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can customize a meal plan for each day of the week. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create a meal plan for every day of the week.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141405727-aae1c9f5-554b-4a9d-9d34-563a832d669c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  Pick a nice font pair from Google Fonts for headings and body text.
- [x]  Pick a nice accent color.
- [x] Create a simple, polished header in HTML and CSS that shows the name of the application.
- [x] Create a page where the User can enter in a the meal information for the specific day.
- [x] After clicking "save" it stores the data into the database and takes the User to the day of the week that was chosen to add a meal with the new meal being displayed.
- [x] Handle all errors and respond to the client
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
