### ISSUE TITLE
Feature: Users can create a workout regimen for each day of the week.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can create a workout regimen for each day of the week.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to create their own exercises for each day of the week.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141407531-15cdf413-78ef-4719-b3b6-d1e94af48cce.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a page where the User can enter in a the exercise information for the specific day.
- [x] After clicking "save" it stores the data into the database and takes the User to the day of the week that was chosen to add an exercise with the new exercise being displayed.
- [x] Handle all errors and respond to the client
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
