### ISSUE TITLE
Feature: Users can utilize a calorie calculator to find out how many calories they must consume everyday to lose weight.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view how many calories they need to consume on a daily basis to loose weight.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can enter in their Gender, Age, Weight, Height, and Activity Level to view how many calories they need to consume on a daily basis to loose weight.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141409109-81abff3d-bfbc-46bb-ad3b-b36c38e527cb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
