### ISSUE TITLE
Feature Users can edit meal plans.

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can edit and meal plans
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can edit and view revised meal plans
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141410232-3905be89-c6a3-4a66-acf3-145ba2963623.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a page where the User can update the information for the specific meal chosen.
- [x] After clicking "update meal", a http request is sent to the backend using a "fetch" to the "app.fetch" to update the meal.
- [x] The new and revised meal is displayed in the correct day of the week it belonged to. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
