### ISSUE TITLE
Feature: User can edit workout regimens

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit workout regimens
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can edit and view revised workout regimens
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141411805-729fd774-9c21-481e-8b70-38c37e2c1d24.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a page where the User can update the information for the specific exercise chosen.
- [x] After clicking "update Exercise", a http request is sent to the backend using a "fetch", to the "app.fetch" to update the exercise.
- [x] The new and revised exercise is displayed in the correct day of the week it belonged to. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
