### ISSUE TITLE
Feature: User can delete meal plans

### ISSUE THREAD

**Issue by Youssef-Najjarine** [Youssef-Najjarine/Fitness-Pal#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete meal plans
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can delete meal plans
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/71291742/141412424-e8685eab-acac-4c0b-96e0-71cc9dec7fac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] After clicking "Delete Icon", a http request is sent to the backend using a "fetch", to the "app.delete" to delete the meal plan.
- [x] The meal is currently not displayed anymore. 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
